// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package hotdata

import (
	"database/sql"

	"github.com/google/uuid"
)

type BrandlovrsCalendar struct {
	Date    sql.NullTime
	Year    sql.NullInt32
	Month   sql.NullInt32
	Day     sql.NullInt32
	Dow     sql.NullInt32
	Week    sql.NullInt32
	Quarter sql.NullInt32
}

type BrandlovrsVBrandTotalBalance struct {
	BrandID               sql.NullInt32
	Name                  sql.NullString
	WalletCredits         sql.NullString
	Provisioned           sql.NullString
	ReservedDebit         sql.NullString
	Reserved              sql.NullString
	EngRewardsPaidOld     sql.NullString
	EngRewardsPaidCurrent sql.NullString
	TotalRandomPayments   sql.NullString
	AdjustDebits          sql.NullString
	Available             sql.NullString
}

type BrandlovrsVMBrand struct {
	BrandID              sql.NullInt32
	Brand                sql.NullString
	Cnpj                 sql.NullString
	CompanyName          sql.NullString
	Interest             sql.NullString
	Challenges           sql.NullInt32
	ActiveChallenges     sql.NullInt32
	TotalAmbassadors     sql.NullInt32
	AmbassadorsWithSales sql.NullInt32
	TotalSales           sql.NullString
	BrandlovrsRate       sql.NullString
	Gmv                  sql.NullString
	Gmv7                 sql.NullString
	Gmv15                sql.NullString
	Gmv30                sql.NullString
	Gmv60                sql.NullString
	Gmv90                sql.NullString
	LastSale             sql.NullTime
	ProvisionedBalance   sql.NullString
	ReservedBalance      sql.NullString
	AvailableBalance     sql.NullString
	CreatedAt            sql.NullTime
	Status               sql.NullBool
	BrandActivity        sql.NullString
	BrandLogoUrl         sql.NullString
}

type BrandlovrsVMBrandWalletHistory struct {
	BrandID         sql.NullInt32
	BrandName       sql.NullString
	MissionID       sql.NullInt32
	MissionName     sql.NullString
	ChallengeType   sql.NullString
	Value           sql.NullString
	OrderID         sql.NullString
	TransactionDate sql.NullTime
	SourceBalance   sql.NullString
	TargetBalance   sql.NullString
	TransactionType sql.NullString
	Details         sql.NullString
}

type BrandlovrsVMInstagramProfilesBrand struct {
	BrandID                      sql.NullInt32
	InstagramID                  sql.NullString
	InstagramUsername            sql.NullString
	InstagramFullname            sql.NullString
	InstagramIgtvvideocount      sql.NullInt32
	InstagramPostscount          sql.NullInt32
	InstagramFollowerscount      sql.NullInt32
	InstagramFollowscount        sql.NullInt32
	InstagramDataIngestion       sql.NullString
	InstagramBiography           sql.NullString
	InstagramPrivate             sql.NullBool
	InstagramVerified            sql.NullBool
	InstagramProfileUrl          sql.NullString
	InstagramProfilePictureUrl   sql.NullString
	InstagramProfilePictureUrlHd sql.NullString
}

type BrandlovrsVMInstagramProfilesUser struct {
	UserID                       sql.NullInt32
	InstagramID                  sql.NullString
	InstagramUsername            sql.NullString
	InstagramFullname            sql.NullString
	BusinessCategory             sql.NullString
	InstagramIgtvvideocount      sql.NullInt32
	InstagramPostscount          sql.NullInt32
	InstagramFollowerscount      sql.NullInt32
	InstagramFollowscount        sql.NullInt32
	InstagramDataIngestion       sql.NullString
	InstagramBiography           sql.NullString
	InstagramPrivate             sql.NullBool
	InstagramVerified            sql.NullBool
	InstagramProfileUrl          sql.NullString
	InstagramProfilePictureUrl   sql.NullString
	InstagramProfilePictureUrlHd sql.NullString
}

type BrandlovrsVMTotalCouponSale struct {
	BrandID            sql.NullInt32
	BrandName          sql.NullString
	OrderID            sql.NullString
	BlCoupon           sql.NullString
	CouponCreationDate sql.NullTime
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	Total              sql.NullString
	Discount           sql.NullString
	Status             sql.NullString
	FStatus            sql.NullString
	MissionID          sql.NullInt32
	MissionName        sql.NullString
	TypeReward         sql.NullInt32
	IsApplyTakeRate    sql.NullBool
	PaymentDays        sql.NullInt32
	RewardValue        sql.NullString
	UserID             sql.NullString
	UserName           sql.NullString
	UserEmail          sql.NullString
}

type CoreWorkspace struct {
	ID           uuid.NullUUID
	CustomerID   uuid.NullUUID
	Email        sql.NullString
	Name         sql.NullString
	ReferenceID  sql.NullString
	IntegratorID sql.NullInt32
	Active       sql.NullBool
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	Type         sql.NullString
}

type DatahubExecutionHistoryLog struct {
	ID           uuid.NullUUID
	TableName    sql.NullString
	ExecutedAt   sql.NullTime
	TotalRecords sql.NullInt64
}

type EcommerceFactOrder struct {
	PkID         sql.NullInt32
	ConnectorTag sql.NullString
	WorkspaceID  uuid.NullUUID
	SourceID     uuid.NullUUID
	ConnectionID uuid.NullUUID
	OrderID      sql.NullString
	CustomerID   sql.NullString
	Total        sql.NullString
	Shipping     sql.NullString
	Discount     sql.NullString
	CancelReason sql.NullString
	Currency     sql.NullString
	InternalID   sql.NullInt32
	Source       sql.NullString
	Details      sql.NullString
	Status       sql.NullString
	Active       sql.NullBool
	ProcessedAt  sql.NullTime
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	CancelledAt  sql.NullTime
}

type RdsMysqlBrandDnb struct {
	ID                      int32
	Name                    sql.NullString
	Url                     sql.NullString
	BrandBannerUrl          sql.NullString
	FkIDAcceptRule          sql.NullInt32
	About                   sql.NullString
	CreatedAt               sql.NullTime
	ChurnDate               sql.NullTime
	ChurnFinishedAt         sql.NullTime
	Isactive                sql.NullBool
	DatahubWorkspaceID      sql.NullString
	BrandLogoUrl            sql.NullString
	BrandBannerUrlThumb     sql.NullString
	NumberOfEmployeesID     sql.NullInt32
	AverageMonthlyRevenueID sql.NullInt32
	BrandLogoUrlThumb       sql.NullString
	MinimumBalance          sql.NullString
	Cnpj                    sql.NullString
	FkIDBrandStatus         sql.NullInt32
	ForceApplyTakeRate      sql.NullBool
	AlwaysApplyTakeRate     sql.NullBool
	CompanyName             sql.NullString
}

type RdsMysqlBrandDnbXColabUser struct {
	ID                            sql.NullInt32
	FkIDColabUser                 sql.NullInt32
	FkIDBrandDnb                  sql.NullInt32
	FkIDBrandDnbXInfluencerInvite sql.NullInt32
	FlagApplyTakeRate             sql.NullBool
}

type RdsMysqlBrandDnbXInfluencerInvite struct {
	ID                sql.NullInt32
	FkIDBrandDnb      sql.NullInt32
	FkIDColabUser     sql.NullInt32
	Acceptedat        sql.NullTime
	Createdat         sql.NullTime
	Rejectedat        sql.NullTime
	FlagWhoInvited    sql.NullBool
	FlagApplyTakeRate sql.NullBool
}

type RdsMysqlColabCoupon struct {
	ID                     sql.NullInt32
	CreatedAt              sql.NullTime
	ExpiresAt              sql.NullTime
	InfluencerCouponPrefix sql.NullString
	Quantity               sql.NullInt32
	FkIDColabUser          sql.NullInt32
	FkIDMissionXCouponInfo sql.NullInt32
	EcommerceCouponID      sql.NullString
	AmountOfUse            sql.NullInt32
	LastUse                sql.NullTime
}

type RdsMysqlColabLevelsXMissionsXReward struct {
	FkIDColabMissions   sql.NullInt32
	FkIDColabLevels     sql.NullInt32
	FkIDColabTypeReward sql.NullInt32
	GrossValue          sql.NullString
	Value               sql.NullString
}

type RdsMysqlColabMission struct {
	ID                  int32
	Title               sql.NullString
	Description         sql.NullString
	FkIDColabSubmission sql.NullInt32
	FkIDBrandDnb        sql.NullInt32
	FkIDColabReward     sql.NullInt32
	CreatedAt           sql.NullTime
	ExpiredAt           sql.NullTime
	Status              sql.NullBool
	PaymentDays         sql.NullInt32
	DeletedAt           sql.NullTime
	ShopifyPriceRuleID  sql.NullString
	PriceRuleSetup      sql.NullString
	MinimumSubtotal     sql.NullString
	Banner              sql.NullString
	ThumbBanner         sql.NullString
	RewardDescription   sql.NullString
	CumulativeDiscount  sql.NullBool
	ChallengeStatusID   sql.NullInt32
	MaxValuePerOrder    sql.NullString
	UtmSource           sql.NullString
}

type RdsMysqlColabMissionsXColabUser struct {
	ID                int32
	FkIDColabMissions sql.NullInt32
	FkIDColabUser     sql.NullInt32
	Status            sql.NullBool
	FlagApplyTakeRate sql.NullBool
}

type RdsMysqlColabUser struct {
	ID                     int32
	Name                   sql.NullString
	Email                  sql.NullString
	Password               sql.NullString
	Isactive               sql.NullBool
	FkIDColabUserInvite    sql.NullInt32
	Termsuse               sql.NullBool
	Emailconfirmationtoken sql.NullString
	Token                  sql.NullString
	CreatedAt              sql.NullTime
	UpdatedAt              sql.NullTime
	Username               sql.NullString
	Avatar                 sql.NullString
	ThumbAvatar            sql.NullString
	TokenPush              sql.NullString
	CreatorSizeID          sql.NullInt32
	LastSocialReportSync   sql.NullTime
	Activity               sql.NullString
	FirstAccess            sql.NullBool
}

type RdsMysqlColabUserDatum struct {
	ID                 sql.NullInt32
	Value              sql.NullString
	FkIDColabTypeLabel sql.NullInt32
	FkIDColabUser      sql.NullInt32
}

type RdsMysqlMissionXCouponInfo struct {
	ID                     sql.NullInt32
	ExpiresAt              sql.NullTime
	TotalQuantity          sql.NullInt32
	BrandPrefix            sql.NullString
	Value                  sql.NullString
	FkIDCouponTypeDiscount sql.NullInt32
	FkIDColabMission       sql.NullInt32
	MaxUsePerCreator       sql.NullInt32
}

type SocialMetricsVMPostMetric struct {
	PostID          int64
	SocialNetworkID sql.NullInt32
	Url             sql.NullString
	ProfileID       sql.NullInt64
	LastUpdated     sql.NullTime
	Likes           sql.NullInt32
	Comments        sql.NullInt32
	Plays           sql.NullInt32
	Shares          sql.NullInt32
}

type SocialMetricsVMSnPostHashtag struct {
	UserID    sql.NullInt32
	Name      sql.NullString
	ProfileID sql.NullInt64
	PostID    sql.NullInt64
	CreatedAt sql.NullTime
	MediaID   sql.NullInt32
	HashtagBl sql.NullString
}
